services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    container_name: example-web
    ports:
      - ${PORT:-8080}:8080
    environment:
      - PRODUCTION=true
      - DATABASE_URL=jdbc:postgresql://db:5432/${DATABASE_NAME:-example}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:12-alpine
    container_name: example-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-example}
      - POSTGRES_USER=${DATABASE_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: example-data
    external: true
