# fly.toml app configuration file generated for java-docker-tutorial on 2023-11-24T14:13:58-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "java-docker-tutorial"
primary_region = "scl"

[build]

[env]
  DATABASE_DIALECT = "org.hibernate.dialect.PostgreSQLDialect"
  DATABASE_DRIVER = "org.postgresql.Driver"
  DATABASE_HBM2DDL_AUTO = "validate"
  DATABASE_RESET_CRON = "0 0/2 * * * ?"
  DATABASE_SHOW_SQL = "false"
  PRODUCTION = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
