name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `main`.
on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/publish.yml'
      - 'Dockerfile'
      - 'pom.xml'
      - 'src/**'
  workflow_dispatch:

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: java_app
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
